### ISSUE TITLE
How to convert feats_mapping.lst to tfrecords?

### ISSUE THREAD

**Issue by hlthu** [snsun/pit-speech-separation#13]
I have run the baseline, and I also generate another feats using matlab scripts provided by you, `extract_czt_fft_feats`, and convert it to Kaldi type.

Then I use `local/makelist` to generate a list file as
```
huanglu@speech-WorkStation:pit-speech-separation$ head lists/tt_feats_mapping.lst
050a0501_1.7783_442o030z_-1.7783.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:37 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:39 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:141477
050a0502_1.3461_440o030j_-1.3461.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:281761 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:282915 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:438801
050a0502_1.463_420a010o_-1.463.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:592267 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:594685 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:750569
050a0502_1.9707_440c020w_-1.9707.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:902775 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:906455 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:1062341
050a0504_2.4414_443o0313_-2.4414.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:1213283 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:1218227 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:1398365
050a0505_1.5097_440o030d_-1.5097.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:1572107 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:1578503 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:1767413
050a0506_1.7744_447c0213_-1.7744.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:1948407 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:1956323 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:2108597
050a0506_1.9887_447c0215_-1.9887.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:2251719 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:2260871 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:2444621
050a0507_0.75154_423a010l_-0.75154.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:2617741 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:2628373 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:2811093
050a0508_0.19796_423a010l_-0.19796.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:2981707 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:2993813 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:3160021
```

How can I then convert this one to tfrecords, I am not familiar with the tf.

Thx!

**Comment by snsun** [comment]
Hi, 

Actually, now you don’t need to matlab extract features now. I have python scripts, ./local/gen_tfrecords.py. This script can be used to extract fft features and store them to tfrecords. 

Best


发送自 Windows 10 版邮件应用

发件人: Lu Huang
发送时间: 2018年5月19日 21:23
收件人: snsun/pit-speech-separation
抄送: Subscribed
主题: [snsun/pit-speech-separation] How to convert feats_mapping.lst totfrecords? (#13)

I have run the baseline, and I also generate another feats using matlab scripts provided by you, extract_czt_fft_feats, and convert it to Kaldi type.
Then I use local/makelist to generate a list file as
huanglu@speech-WorkStation:pit-speech-separation$ head lists/tt_feats_mapping.lst
050a0501_1.7783_442o030z_-1.7783.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:37 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:39 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:141477
050a0502_1.3461_440o030j_-1.3461.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:281761 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:282915 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:438801
050a0502_1.463_420a010o_-1.463.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:592267 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:594685 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:750569
050a0502_1.9707_440c020w_-1.9707.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:902775 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:906455 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:1062341
050a0504_2.4414_443o0313_-2.4414.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:1213283 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:1218227 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:1398365
050a0505_1.5097_440o030d_-1.5097.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:1572107 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:1578503 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:1767413
050a0506_1.7744_447c0213_-1.7744.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:1948407 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:1956323 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:2108597
050a0506_1.9887_447c0215_-1.9887.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:2251719 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:2260871 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:2444621
050a0507_0.75154_423a010l_-0.75154.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:2617741 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:2628373 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:2811093
050a0508_0.19796_423a010l_-0.19796.wav /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_inputs/feats.ark:2981707 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:2993813 /home/huanglu/data/WSJ0_Mix/2speakers/feat8k/min/tt_labels/feats.ark:3160021
How can I then convert this one to tfrecords, I am not familiar with the tf.
Thx!

**Comment by hlthu** [comment]
Yes, I have used that one, but sometimes I want to use some feats from Kaldi, could you please give me some suggestions?

Thx for you reply!

Lu Huang

**Comment by snsun** [comment]
There are there files you can refer to: 
1. Io_funcs/kaldi_io.py. This code is used to read data from kaldi scp and ark files;
2. Io_funcs/tfrecords_io.py. Function in his file is used to make mini_batch for LSTM training from tfrecords files during LSTM training. 
3. Local/gen_tfrecords.py.  After you read kaldi feats, you can refer to function ‘gen_feats’ in this file to convert them to tfrecords.

Best
Sining

发送自 Windows 10 版邮件应用

发件人: Lu Huang
发送时间: 2018年5月19日 21:28
收件人: snsun/pit-speech-separation
抄送: Sining Sun; Comment
主题: Re: [snsun/pit-speech-separation] How to convert feats_mapping.lst totfrecords? (#13)

Yes, I have used that one, but sometimes I want to use some feats from Kaldi, could you please give me some suggestions?

Thx for you reply!

Lu Huang

**Comment by hlthu** [comment]
Thx so much

Lu Huang
