### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 1488 and 992 for 'model/blstm/stack_bidirectional_rnn/cell_0/bidirectional_rnn/fw/fw/while/fw/basic_lstm_cell/MatMul_2' (op: 'MatMul') with input shapes: [25,1488], [992,1984].

### ISSUE THREAD

**Issue by pchao6** [snsun/pit-speech-separation#15]
Problem: 
(1) tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 1488 and 992 for 'model/blstm/stack_bidirectional_rnn/cell_0/bidirectional_rnn/fw/fw/while/fw/basic_lstm_cell/ MatMul_2' (op: 'MatMul') with input shapes: [25,1488], [992,1984].
(2) ValueError: Dimensions must be equal, but are 1488 and 992 for 'model/blstm/stack_bidirectional_rnn/ cell_0/bidirectional_rnn/fw/fw/while/fw/basic_lstm_cell/MatMul_2' (op: 'MatMul') with input shapes:[25,1488], [992,1984].

@snsun I guess it might be the reason for the tensorflow version (your tensorflow version is 1.0 ?). What do you think of it? Thanks!

**Comment by snsun** [comment]
Yes. I have met the same problem. I have fixed this and you can try it now. If there are any problems, please let me know. 
Thanks.

**Comment by pchao6** [comment]
@snsun My Tensorfow version is 1.4.0. Solve it! Thanks!
