### ISSUE TITLE
A problem when preparing my own data for TFRecords format.

### ISSUE THREAD

**Issue by eeZhangqj** [snsun/pit-speech-separation#16]
Hi! I am a college student. I was studying your projects these days and got some problems. 
I did not find the function "make_sequence_example_two_labels" in the "io_funcs" folder. Was it an error?And I was not really sure about how to generate the required TFRecords using my own data. Or would it be possible that we contact on Wechat? Many thanks!

**Comment by eeZhangqj** [comment]
I just notice that I can also use gen_tfrecords.py rather than those matlab scripts. It seems that there are four args to provide in gen_tfrecords.py: wavdir, namelist, tfdir, gender_list. But I am not sure what they are look like. Can you explain them more clearly?

**Comment by snsun** [comment]
Hi,

You can add my Wechat. Email me your wechat ID by your personal email.

Best
Sining

2018-08-08 22:35 GMT+08:00 Qijian Zhang <notifications@github.com>:

**Comment by eeZhangqj** [comment]
thx, I have sent it to your email.
