### ISSUE TITLE
run.sh

### ISSUE THREAD

**Issue by ujscjj** [snsun/pit-speech-separation#22]
Hello.Sorry to bother you.
`python -u local/gen_tfreords.py --gender_list local/wsj0-train-spkrinfo.txt data/wav/wav8k/min/$x/ lists/${x}_wav.lst data/tfrecords/${x}_psm/ &`
I cannot get the _wav.lst. Could please tell me where does it come from?Thank you very much.
Or ,could we chat in Wechat or QQ please?

**Comment by snsun** [comment]
Hi,

If you have WSJ0 data, it would be easy. You can generate mixed wav using
the matlab code. If you have other questions, send me your wechat id to my
personal email address.

Best


ujscjj <notifications@github.com> 于2019年1月17日周四 下午10:15写道：
