### ISSUE TITLE
what‘s meta-frame's meaning?

### ISSUE THREAD

**Issue by lvyilan23** [snsun/pit-speech-separation#23]
1.I don't understand meta-frame's meaning.

2.how to choose the least total MSE , as the model parameters haven't been optimized yet.

maybe my question sounds like a little fool,i am sooo new to ml.

**Comment by snsun** [comment]
Hi,

1. Meta-frame means that the concatenated-frame. For example, for the
current frame, X_t, you can concatenate the previous T frame and the next T
frame together to make a meta-frame. Hence a meta-frame X^M_t = [X_{t-T},
X_{t-T+1}, ... X_{t-1}, X_t, X_{t+1}, ..., X_T];
2. I didn't understand your second question.

Best

lvyilan23 <notifications@github.com> 于2019年2月18日周一 下午8:52写道：
