### ISSUE TITLE
I have some problems with executing code.

### ISSUE THREAD

**Issue by yctsai77** [snsun/pit-speech-separation#24]
Hello, sorry to bother you.
I am a student and just getting into machine learning.
Recently studied paper and code for speech separation.
I want to execute your program, but I have some problems.
Because I don't have WSJ0 data, so I use TIMIT dataset.
And slightly modify the matlab code you provided to produce a mixed speech.
But I don't quite understand how to extract the spectral features and labels of each utterance in python.
Execute gen_tfreords.py separately with Spyder (2.7 or 3.7), an error like No module named 'io_funcs.signal_processing' will appear.
Or would it be possible that we contact on Wechat OR Email? Many thanks!

**Comment by snsun** [comment]
hi,

You can send your WeChat ID to my personal email using your personal email
if you have more questions about my code.


yctsai77 <notifications@github.com> 于2019年2月21日周四 下午3:49写道：
